name: build and push

on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "wai-calvin"
          password: ${{ secrets.PAT }}
          repository: wai-calvin/react-redux-realworld-example-app
          tags: latest